# Generated by Django 4.1.7 on 2026-02-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_about', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('survivor_accounts', models.BooleanField(default=False)),
                ('tailored_content', models.BooleanField(default=False)),
                ('statistics', models.BooleanField(default=False)),
                ('victim_focused', models.BooleanField(default=False)),
                ('risk_reduction', models.BooleanField(default=False)),
                ('partnerships', models.BooleanField(default=False)),
                ('overall_definition', models.BooleanField(default=False)),
                ('trafficking_signs', models.BooleanField(default=False)),
                ('law_enforcement', models.BooleanField(default=False)),
                ('legal_regulations', models.BooleanField(default=False)),
                ('pretest', models.BooleanField(default=False)),
                ('posttest', models.BooleanField(default=False)),
                ('interactive', models.BooleanField(default=False)),
                ('languages', models.TextField(help_text='Comma-separated list of languages')),
                ('logo_path', models.CharField(blank=True, max_length=255)),
                ('total_score', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
