# Generated by Django 4.1.7 on 2026-02-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysubmission',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Admin approval status for adding to website', max_length=20),
        ),
        migrations.AddField(
            model_name='surveysubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveysubmission',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
